### ISSUE TITLE
\Debug\ultra_simple.exe not openning

### ISSUE THREAD

**Issue by DucAnh-Vu-Trinh** [Slamtec/rplidar_sdk#103]
I built the solution in VS2019 and tried to run the file ultra_simple.exe, but nothing opened. Do I need to do anything after build the solution? Please advise.

**Comment by deyouslamtec** [comment]
Execute in CMD or Windows Terminal
![image](https://github.com/Slamtec/rplidar_sdk/assets/129710377/05b14f30-c62b-492f-b0b6-a306f2cf515a)
