### ISSUE TITLE
dead SDK link

### ISSUE THREAD

**Issue by HourGlss** [Slamtec/rplidar_sdk#107]
https://download.slamtec.com/api/download/rplidar-sdk-manual/1.0?lang=en

link is dead.

I'm trying to get information about the serial connection and what the GND_MOTO CTRL_MOTO and 5V_MOTO pins are for.

I believe that's ground, PWM for ctrl_moto and 5v?

ANY information concerning the UART? I2C? Serial data lines on the tx,rx pins for the A1M8-R6 device would be great.

**Comment by deyouslamtec** [comment]
support page：https://www.slamtec.com/en/Support#rplidar-a-series
