### ISSUE TITLE
RoboStudio not available

### ISSUE THREAD

**Issue by y-vega** [Slamtec/rplidar_sdk#111]
Hi!
I would like to start  witch my new S2 on Windows
But RoboStudio is not available on link https://www.slamtec.com/robostudio. What can I do?
can you help me?
thanks

**Comment by y-vega** [comment]
no, i didn't download anything, the software is not available,
the published link to download it does not lead to any web page or file

**Comment by deyouslamtec** [comment]
Try using this download link. If not, you can leave your email address and I will send it to you
download link: https://bucket-download.slamtec.com/4e6915fd6e0095c6033205a57e537b21ce99447e/install_robostudio_20230419.zip
