### ISSUE TITLE
unable to make the SDK

### ISSUE THREAD

**Issue by r8drfn89** [Slamtec/rplidar_sdk#116]
![DB6AE89D-583B-4A1C-9FBB-B3F16491DF5F](https://github.com/Slamtec/rplidar_sdk/assets/137663045/9f5c0f79-dbff-467c-830b-d020863a5eed)

I cloned the repository for the sdk. Then in the root of the sdk I tried to run make. These are the errors I get. 

sudo make and make DEBUG=1 also fail and give this same errors

**Comment by r8drfn89** [comment]
I even tried it in the rplidar_sdk/sdk       still gives the same error
![6F76604E-4D8C-4375-8722-5A42B3768F28](https://github.com/Slamtec/rplidar_sdk/assets/137663045/28d3b63a-4808-45bc-8c8b-33ff4c228086)

**Comment by deyouslamtec** [comment]
Try dev-sdk branch, the latest commit may solve this problem

**Comment by r8drfn89** [comment]
@deyouslamtec What do you mean dev-sdk branch?

**Comment by deyouslamtec** [comment]
![image](https://github.com/Slamtec/rplidar_sdk/assets/129710377/b3690cf8-41be-4c76-950f-cac7acd3ae40)

**Comment by r8drfn89** [comment]
Okay thanks for showing where to click. Still does not explain what to do. Am I supposed to clone from that branch?

**Comment by deyouslamtec** [comment]
yes. clone or download dev-sdk branch

**Comment by r8drfn89** [comment]
![06D65376-76C4-4265-9B7D-C70F308283E9](https://github.com/Slamtec/rplidar_sdk/assets/137663045/9478334c-3f88-4435-afe6-9cd07a4bb433)
@deyouslamtec I tried what you suggested and the same error is occurring during the make.

**Comment by deyouslamtec** [comment]
please run `git clone -b dev-sdk https://github.com/Slamtec/rplidar_sdk.git` to clone dev-sdk branch

**Comment by r8drfn89** [comment]
I have successfully downloaded the sdk and went through the make. Now I am getting an error trying to run the applications. 
![5FEE0A2D-770C-434D-A346-2D368600A081](https://github.com/Slamtec/rplidar_sdk/assets/137663045/178a4f0c-2b64-4e97-9461-235c972fe47c)
Where am I supposed to run the demo application?

**Comment by deyouslamtec** [comment]
The APP executable file is in the rplidar_sdk/output/Linux/Release/ directory
