### ISSUE TITLE
Suggestion on how your might get 256000 on MacOS

### ISSUE THREAD

**Issue by justinh24** [Slamtec/rplidar_sdk#15]
I don't have a Slamtec sensor, but I know when working with other hardware with odd baud rates, rather than using cfsetisspeed and cfsetosspeed you can use an ioctl IOSSIOSPEED.  

   #include <IOKit/serial/ioss.h>
   speed_t speed = (speed_t)256000;
   ioctl(fd, IOSSIOSPEED, &speed);

Hope that is helpful.

**Comment by tony-slamtec** [comment]
Thanks a lot. This feature has been integrated to the new release of SDK.
