### ISSUE TITLE
grabScanDataHq

### ISSUE THREAD

**Issue by Programmer54** [Slamtec/rplidar_sdk#73]
It always returns the same data. What can I do for it ?

**Comment by RickCarp** [comment]
Hi, Were you able to fix that ? I am having the same issue but just by connecting by socket.

**Comment by Programmer54** [comment]
When you run the functions in the sdk, you have to wait for a while until the process is finished. A value is returned whether the operation was successful or not. You can check this value with the "IS_OK()" function. If you switch from one process to the next, I think the device goes into an error state and always returns the same data. Allow the device to perform its operations correctly.
